language: node_js
node_js:
- '6'
- '4'
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: timmywillisn@gmail.com
  api_key:
    secure: fB0aOwYRhjV/1dgAq45ou+QUrT6bmiPwKe82bID65PKqg+Jx1XeHbXzb0Gq9dQLBfecNuFIoHxASzO70jHDPKqlvK+vIAlC5G7h4E93qEHlP5NxgX7sHBtv73gYzsuie420guwqzTyVLuYPTH2G8W8fR5vMD1PaRzS2QMtLEVCWLPNOK5BcDEOsv3MsqK2Jl5XXIM8GGHWvcMo633pyql9ykJcYmo+7hqXg4OULkAU3eDCKs8vcm1wAp9xtNLy7yCfiraFgzmkG0+8wd9s+NwBGkzAMOhk7yaYXvQ2FZz1LXbO18ez1BIODGDZwwZmnfrhSY+1330yfoAET8ZbpKhcqt+XUp/BPL4cyF0sVCsc+wPm8hNiTJr1cHf582lxm6JJrx/LY3QSf5i2CVrh6/CwcOx23bU+LrlTdCQSuSjXzcJb4Ca5iK5SL4GnNkX1+LF9ZPyORst3NLU7JkjifCG0TTU7Yq8S8nm8HLRuQ5eoqkNaXgH+kJAgaVBIY890t1jFhRSv5Jl60KcrN/wvGcB4imjO1bPzIkxK7QF0dKDMKSPlWHxRj8w2vgTFEHFMP/mGGls89Tc32EFTYXzgq6N7wP/xYmFQMv5L6xFKVdOILEG6TBDyE0bKQ/ZCBJu2UeQP8z1fsMkuLa1JKlt23t2oawfCYaFuYi57X+qtCyLSY=
  on:
    tags: true
